version: "3.8"
services:
  web:
    #image: imshuhao/a2web:latest
    image: web
    container_name: web
    ports:
      - "80:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    environment:
      - REDIS_HOST=10.11.1.114,10.11.1.115,10.11.1.23
      - CASSANDRA_CLUSTER=10.11.1.114,10.11.1.115,10.11.1.23
    depends_on:
      - master
    networks:
      - a2network

  writer:
    #image: imshuhao/a2writer:latest
    image: writer
    container_name: writer
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    environment:
      - REDIS_HOST=10.11.1.114,10.11.1.115,10.11.1.23
      - CASSANDRA_CLUSTER=10.11.1.114,10.11.1.115,10.11.1.23
    depends_on:
      - master
    networks:
      - a2network

  master:
    image: redis
    container_name: redis-master
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /home/student/CSC409A2/redis:/data
      - /home/student/redis/overrides.conf:/opt/bitnami/redis/mounted-etc/overrides.conf
      - /home/student/redis/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
      # - /home/student/redis/overrides.conf:/overrides.conf
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 128M
      placement:
        constraints: [node.role == manager]
    command: 
      - bash
      - -c
      - redis-server /opt/bitnami/redis/mounted-etc/redis.conf --maxmemory $$(( $$( cat /sys/fs/cgroup/memory/memory.limit_in_bytes ) - 100000000)) --maxmemory-policy allkeys-random # --appendonly yes
    networks:
      - a2network

  slave:
    image: redis
    container_name: redis-slave
    ports:
      - 6380:6380
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          memory: 128M
      restart_policy:
        condition: on-failure
    volumes:
      - /home/student/redis/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    command: 
      - bash
      - -c
      - redis-server /opt/bitnami/redis/mounted-etc/redis.conf --port 6380 --replica-announce-port 6380 --replicaof master 6379 --maxmemory $$(( $$( cat /sys/fs/cgroup/memory/memory.limit_in_bytes ) - 100000000)) --maxmemory-policy allkeys-random # --appendonly yes
    depends_on:
      - master
    networks:
      - a2network

  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    ports:
      - 26379:26379
    environment:
      - REDIS_MASTER_HOST=10.11.1.114
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=20000
      - REDIS_SENTINEL_RESOLVE_HOSTNAMES=yes
      # - REDIS_SENTINEL_ANNOUNCE_IP=10.11.1.114
      - REDIS_SENTINEL_ANNOUNCE_PORT=6380
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
    depends_on:
      - master
      - slave
    networks:
      - a2network

networks:
  a2network:
