version: "3.8"
services:
  web:
    #image: imshuhao/a2web:latest
    image: imshuhao/a2web:latest
    ports:
      - "80:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      # placement:
      #   constraints: [node.role == manager]
    environment:
      - REDIS_SENTINEL=redis-sentinel
      - CASSANDRA_CLUSTER=${CASSANDRA_CLUSTER}
    volumes:
      - /home/student/CSC409A2/web/logs/log.txt:/data/log.txt
    depends_on:
      - redis
    networks:
      - a2network

  writer:
    #image: imshuhao/a2writer:latest
    image: imshuhao/a2writer:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      # placement:
      #   constraints: [node.role == manager]
    environment:
      - REDIS_SENTINEL=redis-sentinel
      - CASSANDRA_CLUSTER=${CASSANDRA_CLUSTER}
    depends_on:
      - redis
    networks:
      - a2network

  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /home/student/CSC409A2/redis:/data
      - /home/student/redis/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 128M
      placement:
        constraints: [node.role == manager]
    command: 
      - bash
      - -c
      - redis-server /opt/bitnami/redis/mounted-etc/redis.conf --maxmemory $$(( $$( cat /sys/fs/cgroup/memory/memory.limit_in_bytes ) - 100000000)) --maxmemory-policy allkeys-random # --appendonly yes
    networks:
      - a2network

  slave:
    image: redis
    ports:
      - 6379
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
        constraints: [node.role == worker]
      resources:
        limits:
          memory: 128M
      restart_policy:
        condition: on-failure
    volumes:
      - /home/student/redis/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    # command: 
    #   - bash
    #   - -c
    #   - redis-server /opt/bitnami/redis/mounted-etc/redis.conf --replicaof redis 6379 --maxmemory $$(( $$( cat /sys/fs/cgroup/memory/memory.limit_in_bytes ) - 100000000)) --maxmemory-policy allkeys-random # --appendonly yes
    command: |
      sh -c '\
      redis-server /opt/bitnami/redis/mounted-etc/redis.conf \
      --slave-announce-ip $$(hostname -i) \
      --port 6379 \
      --slaveof redis 6379 \
      --maxmemory-policy allkeys-random \
      ';
    depends_on:
      - redis
    networks:
      - a2network

  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    # ports:
    #   - 26379:26379
    environment:
      - REDIS_MASTER_HOST=${MASTER_HOST}
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=10000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=20000
      - REDIS_SENTINEL_RESOLVE_HOSTNAMES=yes
      - ALLOW_EMPTY_PASSWORD=yes
      # - REDIS_SENTINEL_ANNOUNCE_IP=10.11.1.114
    # volumes:
    #   - 'redis-sentinel-volume:/bitnami'
    # entrypoint: |
    #   bash -c 'bash -s <<EOF
    #   "/bin/bash" -c "cat <<EOF > /sentinel.conf
    #   port 26379
    #   dir /tmp
    #   sentinel monitor redis-cache redis 6379 2
    #   sentinel down-after-milliseconds redis-cache 5000
    #   sentinel parallel-syncs redis-cache 1
    #   sentinel failover-timeout redis-cache 5000
    #   sentinel auth-pass redis-cache 7cBEcwf6mV36Rx3S
    #   EOF"
    #   "/bin/bash" -c "redis-sentinel /sentinel.conf"
    #   EOF'
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 128M
    depends_on:
      - redis
    networks:
      - a2network

networks:
  a2network:

volumes:
  redis-sentinel-volume: