version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: web:latest
    container_name: web
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
    ports:
      - "4000:80"
    depends_on:
      - master
    environment:
      - REDIS_HOST=redis-master
      - CASSANDRA_CLUSTER=cassandra-node
    networks:
      - a2net

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - a2net

  master:
    image: redis
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - "/home/student/redis:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - a2net

  slave:
    image: redis
    container_name: redis-slave
    ports:
      - "6380:6379"
    deploy:
      replicas: 2
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - master
    networks:
      - a2net

networks:
  a2net:
